import Foundation

/// Payloads for previews and view-model tests: the authored examples from docs/contracts/native-exercises/v1/examples,
/// embedded so previews do not depend on the repo layout. Generated once; keep in sync when the examples change.
enum PreviewPayloads {
    static let binaryCall = #"{"prompt":"Ball bounces once on your side, near the kitchen line.","scene":{"kind":"court-diagram","diagramId":"pickleball-court","markers":[{"role":"player","x":0.5,"y":0.62},{"role":"ball","x":0.5,"y":0.35}],"alt":"Pickleball court. You stand just behind the kitchen line; the ball is coming over the net."},"choices":[{"id":"volley","label":"Volley it"},{"id":"bounce","label":"Let it bounce"}],"correctChoiceId":"volley","explanation":{"correct":"You are outside the kitchen, so volleying is legal.","incorrect":"Standing outside the kitchen you may volley. The no-volley rule applies only inside it."},"ruleTag":"Kitchen rule"}"#
    static let decisionScenario = #"{"prompt":"Sunset is near and the weather is turning. What now?","situation":{"narrative":"You are on a ridge trail with a friend.","facts":[{"label":"Current time","value":"4:51 PM"},{"label":"Sunset","value":"6:42 PM"},{"label":"Distance remaining","value":"4.7 miles"},{"label":"Weather","value":"Deteriorating","emphasis":"warning"},{"label":"Elevation gain left","value":"1,200 ft"}]},"options":[{"id":"continue","label":"Continue","verdict":"poor","consequence":"You reach the summit in fading light and storm cloud with a long descent ahead.","considerations":["Daylight math is tight","Weather trending worse"]},{"id":"alternate","label":"Take the alternate route","verdict":"acceptable","consequence":"Shorter, but unfamiliar terrain in worsening conditions.","considerations":["Shorter is good","Unknown trail is a risk"]},{"id":"turnaround","label":"Turn around","verdict":"best","consequence":"You retrace known trail with hours of daylight to spare.","considerations":["Known route","Margin of daylight and safety"]}],"expertNote":"Experienced hikers set a turnaround time in advance and honor it when conditions change.","safetyNote":"This is a learning scenario, not navigation or safety training."}"#
    static let estimateSlider = #"{"prompt":"How long is an NFL game clock?","unit":"minutes","min":30,"max":120,"step":5,"correctValue":60,"tolerance":{"full":5,"partial":15},"explanation":{"correct":"Four 15-minute quarters. Real time is about three hours because the clock stops.","incorrect":"Four 15-minute quarters make 60 minutes of game clock. The clock stops a lot."}}"#
    static let fillTheGap = #"{"prompt":"Complete the sentence.","template":"On {{down}}, the offense must gain {{yards}} yards for a new set of downs.","gaps":[{"id":"down","options":["first","fourth"],"correct":"fourth"},{"id":"yards","options":["5","10"],"correct":"10"}],"explanation":{"correct":"That is why fourth down is such a big decision.","incorrect":"The offense always needs 10 yards total; fourth is the last try."}}"#
    static let hotspotTap = #"{"prompt":"Tap where the strong safety lines up.","diagram":{"diagramId":"football-formation-cover-3","aspectRatio":1.2,"alt":"Overhead diagram of a defensive formation with three deep defenders."},"hotspots":[{"id":"ss","label":"Strong safety","shape":{"kind":"circle","cx":0.62,"cy":0.3,"r":0.06}},{"id":"fs","label":"Free safety","shape":{"kind":"circle","cx":0.4,"cy":0.2,"r":0.06}}],"correctHotspotIds":["ss"],"explanation":{"correct":"The strong safety sits on the side of the tight end.","incorrect":"Find the tight end: the strong safety lines up on that side."}}"#
    static let listeningID = #"{"prompt":"Which instrument is this?","audio":{"asset":"audio/instruments/oboe-a4.m4a","durationMs":4000,"license":"original-swoond","description":"A single reedy, nasal woodwind note.","maxPlays":3},"options":[{"id":"a","text":"Oboe"},{"id":"b","text":"Clarinet"},{"id":"c","text":"Flute"}],"correctOptionId":"a","explanation":{"correct":"The nasal, reedy tone is the oboe, the note orchestras tune to.","incorrect":"Listen for the nasal, reedy edge: that is the oboe."},"listenFor":["Nasal tone","Double reed"]}"#
    static let multipleChoice = #"{"prompt":"How many downs does the offense get to gain 10 yards?","options":[{"id":"a","text":"Three"},{"id":"b","text":"Four"},{"id":"c","text":"Five"}],"correctOptionIds":["b"],"explanation":{"correct":"Four tries to move the ball 10 yards. Gain them and the count resets to first down.","incorrect":"It is four downs. Most teams punt on fourth down instead of gambling.","sayThisLine":"They should have gone for it on fourth down."}}"#
    static let sayThis = #"{"statement":{"speaker":"Sarah","text":"Our secondary is absolutely killing us this year."},"question":"What is she talking about?","options":[{"id":"a","text":"The defensive backs","isCorrect":true},{"id":"b","text":"The kicker","isCorrect":false},{"id":"c","text":"Pass coverage","isCorrect":true},{"id":"d","text":"The stadium staff","isCorrect":false}],"translation":"The players defending against passes are playing badly, and the team is losing because of it.","followUps":[{"line":"Is it the cornerbacks or the safeties?","why":"Shows you know the secondary has two position groups."}]}"#
    static let sequenceOrder = #"{"prompt":"Put the pottery steps in order.","items":[{"id":"wedge","text":"Wedge the clay","why":"Removes air bubbles that can explode in the kiln."},{"id":"center","text":"Center it on the wheel"},{"id":"throw","text":"Throw the walls up"},{"id":"trim","text":"Trim when leather hard"},{"id":"bisque","text":"Bisque fire"}],"explanation":{"correct":"Preparation first, shaping second, firing last.","incorrect":"The order follows the clay: prepare, shape, dry to leather hard, then fire."}}"#
    static let talkTrack = #"{"title":"Hockey night","setting":"She texts after her team wins in overtime.","startingSmooth":50,"exchanges":[{"theirMessage":"OT winner!! Power play goal, we finally got the man advantage.","replies":[{"id":"a","text":"Nice, the power play finally clicked?","smoothDelta":30,"theirResponse":"YES. It had been 0 for 14.","coachNote":"You picked up the term and asked about it."},{"id":"b","text":"Cool, so who won?","smoothDelta":-20,"theirResponse":"...We did. It is in my text.","coachNote":"Read her message first."}]}],"closingNote":"A power play is a two-minute man advantage after a penalty."}"#
    static let termMatch = #"{"prompt":"Match the position to its job.","pairs":[{"id":"qb","term":"Quarterback","definition":"Runs the offense and throws the ball"},{"id":"cb","term":"Cornerback","definition":"Covers wide receivers"},{"id":"k","term":"Kicker","definition":"Kicks field goals and extra points"}],"explanation":{"summary":"Offense scores, defense stops, special teams handles the kicking game."}}"#
    static let timingTap = #"{"prompt":"Tap when the marker hits the gold.","theme":{"label":"Pit stop","resultUnit":"seconds"},"rounds":[{"zoneStartPct":58,"zoneEndPct":74,"sweepSeconds":1.6},{"zoneStartPct":64,"zoneEndPct":76,"sweepSeconds":1.3},{"zoneStartPct":70,"zoneEndPct":79,"sweepSeconds":1.1}],"explanation":{"correct":"Pit crews win races by shaving tenths. Precision beats speed.","incorrect":"A slow stop can cost track position, which is hard to win back.","sayThisLine":"That pit stop cost him three spots."}}"#
    static let visualID = #"{"prompt":"Which one is the Porsche 911?","image":{"asset":"images/cars/porsche-911-rear.jpg","alt":"Rear three-quarter view of a silver sports car with a sloping roofline.","license":"cc-by-4"},"options":[{"id":"a","text":"Porsche 911"},{"id":"b","text":"Chevrolet Corvette"},{"id":"c","text":"Audi TT"}],"correctOptionId":"a","explanation":{"correct":"The sloping fastback roofline and rear-engine proportions are the 911 signature.","incorrect":"Look at the rear-engine, sloping roofline: that is the 911."},"cues":["Round headlights","Sloping fastback roof"]}"#
}
